"""Creating medications and medicines tables

Revision ID: 83229ea1d220
Revises: 90a2d9968c9b
Create Date: 2021-07-30 20:27:46.690461

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "83229ea1d220"
down_revision = "90a2d9968c9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medicines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Unicode(length=50), nullable=False),
        sa.Column("dosage", sa.Unicode(length=30), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("medicine_id", sa.Integer(), nullable=True),
        sa.Column("gave_at", sa.DateTime(), nullable=True),
        sa.Column("note", sa.UnicodeText(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["medicine_id"], ["medicines.id"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("medications")
    op.drop_table("medicines")
    # ### end Alembic commands ###
