"""Creating tables to save data for Rafa breastfeeding

Revision ID: 90a2d9968c9b
Revises: 
Create Date: 2021-07-06 05:57:46.709796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a2d9968c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaper_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('has_pee', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('has_poop', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milk_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Unicode(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('breastfeeding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milk_source_id', sa.Integer(), nullable=True),
    sa.Column('diaper_change_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diaper_change_id'], ['diaper_changes.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['milk_source_id'], ['milk_sources.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breastfeeding')
    op.drop_table('milk_sources')
    op.drop_table('diaper_changes')
    # ### end Alembic commands ###
